Enhancement: support for burstable instances #66
oracle-terraform-modules/terraform-oci-compute-instance pull request #89
Opened 2022-01-14 16:35 UTC by jlecerf62

Added the support for burstable parameter on compute instance

2022-01-14 16:56 UTC, kral2 requested changes
lgtm regarding bustable instance argument.

three things before being able to merge this contribution:

1. GPG sign your commits (Org policy) : https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
2. update the documentation to reflect your changes: `docs/terraformoptions.adoc` and `examples/`

also, please run `terraform fmt` before committing code.

2022-01-17 13:53 UTC, kral2 approved these changes

2022-01-17 13:56 UTC, kral2 commented
Just update the documentation to reflect your changes (`docs/terraformoptions.adoc` and `examples/`) and we are good for merging.

2022-01-17 14:36 UTC, jlecerf62 commented
GPG signed and documentation updated

2022-01-18 19:20 UTC, kral2 approved these changes

2022-01-18 19:21 UTC, merged